### ISSUE TITLE
Suricata 7.0.1 threads can't be processed

### ISSUE THREAD

**Issue by jcurzon404** [corelight/suricata_exporter#11]
Testing v0.2.0 of suricata_exporter against Suricata 7.0.1 produces this error:

```
panic: interface conversion: interface {} is float64, not map[string]interface {}

goroutine 11 [running]:
main.produceMetrics(0xc000030840?, 0xc00002e1e0?)
	/home/runner/work/suricata_exporter/suricata_exporter/main.go:742 +0x2af
main.(*suricataCollector).Collect(0xc0001b5070, 0xc000046f60?)
	/home/runner/work/suricata_exporter/suricata_exporter/main.go:789 +0x14f
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:448 +0x11a
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:457 +0x4c5
```

These are the threads I see from `suricatasc -c dump-counters`, noting "memcap_pressure" and "memcap_pressur_max" can't be handled in `produceMetrics` as-is.

```
    "threads": {
        "FM#01": { 
            ...
        },
        "FR#01": {
            ...
        },
        "Global": {
            ...
         },
        "W#01-eth0": {
            ...
        },
        "W#02-eth0": {
            ...
        },
        "W#03-eth0": {
            ...
        },
        "W#04-eth0": {
            ...
        },
        "memcap_pressure": 5,
        "memcap_pressure_max": 5
    }
```

https://github.com/corelight/suricata_exporter/pull/10 solves the problem, but by completely ignoring the metrics.

**Comment by jlucovsky** [comment]
I'd suggest a redmine feature/bug.

**Comment by awelzel** [comment]
https://redmine.openinfosecfoundation.org/issues/6398

**Comment by awelzel** [comment]
Thanks yo for the report and directly contributing a fix @jcurzon404 , much appreciated. Could you try v0.2.1 with Suricata 7.0.1?

Thanks!

**Comment by jcurzon404** [comment]
Confirmed that v0.2.1 works with Suricata 7.0.1.

Thanks very much!
